FROM node:22-slim
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /client
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 7777
CMD ["sh", "-c", "sleep 60 && npm run dev"]
